[build-system]
requires = [
	"setuptools>=59.2.0",
	"wheel>=0.37.0"
]
build-backend = "setuptools.build_meta"

[tool.isort]
supported_extensions = ["py"]

# profile =
# 3 - Vertical Hanging Indent
multi_line_output = 3

color_output = true
# Enabling verbose injects messages into file with vim-ale
# TODO: investigate message injection
verbose = false

# Enabling quiet will cause isort to only report errors
quiet = false

line_length = 120

indent = "\t"

use_parentheses = true
include_trailing_comma = true
force_grid_wrap = 2
balanced_wrapping = false

sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

known_third_party = "pytest"

# Name of section for any import statement of a package not known to ‘isort’.
default_section = "LOCALFOLDER"

import_heading_firstparty = "First Party Library"
import_heading_future = "Future Compatability"
import_heading_localfolder = "App"
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Third Party Library"

src_paths = ["src", "tests"]
virtual_env = ".venv"

filter_files = true

skip_gitignore = false
skip = [".git", ".idea", ".pytest_cache", ".venv", ".vscode", "__pycache__", "build,dist", "docs"]
skip_glob = [
	".eggs/**",
	".git/*",
	".venv/*",
	"_build/*",
	"build/*",
	"dist/*",
	# Add additional patterns here:
	"docs/source/conf.py" # File aut-generated by sphinx
]
lines_before_imports = 0
lines_between_sections = 1
lines_between_types = 0
lines_after_imports = 2
ensure_newline_before_comments = true

combine_as_imports = true
combine_star = true
remove_redundant_aliases = true

order_by_type = true

length_sort = false

ignore_comments = true


[tool.pytest.ini_options]
log_cli = true
log_cli_format = "[%(levelname)-8s] %(message)s"
log_cli_level = "INFO"
pythonpath = [
	".",
	"hex_system",
]
testpaths = [
	"tests"
]
